language: python
python:
- '2.7'
- '3.6'
script: python test.py
deploy:
  provider: pypi
  user: maxpowel
  password:
    secure: bE6fe/4F8mOr/0ws+sDaH0Oms5yZdclfUSiLLNGLAHHfCFUtTvrfs0czs3svwhFdjEhlskyzfZHSmzaelgy7QUq58CPTf0i85702jkdvRP5tsJ3TBvi015svyriBq4HqtwJ4ktfOFx9HqSrQbogTuNVXzrK5IOhxRqup+sQmLdSo/V3c7p976emWThpwup+JWyU3HcyegWmJ6HgbtUAz77mELSmQDHkaSnzLakVy0+A3uD50jQshZ9qW8TNii8aq92BMabqaO3KxkfAj8gSmvmjGy7GtvwNx9KibHo7tafupWC+HYNK2JYRcIEIsQeTfnN8BHysAc9GkQvKe+CT9S3zX09009c4hfZ4uJ7JhuC0otVRVf2QJG4dvOJYm2wHmYBs1Iwkv4oseCzeTait6UXiYpQihQaCpPh9evQzROYKyPUZLaQRxvWUfgA+N9Rj9C/liQA2xuRcdvFCa7kBnCNAQGNUFRVE3P/l0J92xY3bJxdxLmYIyZDawifEjtiUPAFTzkv2dKeMiv8W/mFe/EtPhIRAbvnkr+Ex/6NdmNoKwZousSF+taUa3AAQekxcR7aqXPp7lQiJ7rqfOgGdbMld9wtEbPMZqOSr4zBPSFYJboUU7BFC9eh2r8Wy7xhF1FunzzvJq5i5LDwy6CisXTYuwNX4khVdI5Zh0r55kRR0=
  distributions: sdist bdist_wheel
  on:
    tags: true
